# fly.toml app configuration file generated for prueba-test-youtube on 2023-05-01T16:19:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prueba-test-youtube"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
